// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrucutredAPI1.Data;

#nullable disable

namespace StrucutredAPI1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StrucutredAPI1.Data.Course", b =>
                {
                    b.Property<int>("C_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            C_id = 1,
                            CourseName = "Mathematics"
                        },
                        new
                        {
                            C_id = 2,
                            CourseName = "Physics"
                        },
                        new
                        {
                            C_id = 3,
                            CourseName = "Computer Science"
                        },
                        new
                        {
                            C_id = 4,
                            CourseName = "English Literature"
                        },
                        new
                        {
                            C_id = 5,
                            CourseName = "Economics"
                        });
                });

            modelBuilder.Entity("StrucutredAPI1.Data.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Aarav Sharma",
                            age = 20
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Priya Mehta",
                            age = 21
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Rohan Gupta",
                            age = 19
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Sneha Verma",
                            age = 22
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Arjun Patel",
                            age = 20
                        });
                });

            modelBuilder.Entity("StrucutredAPI1.Data.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("C_id")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "C_id");

                    b.HasIndex("C_id");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            C_id = 1
                        },
                        new
                        {
                            StudentId = 1,
                            C_id = 3
                        },
                        new
                        {
                            StudentId = 2,
                            C_id = 2
                        },
                        new
                        {
                            StudentId = 3,
                            C_id = 1
                        },
                        new
                        {
                            StudentId = 4,
                            C_id = 4
                        },
                        new
                        {
                            StudentId = 5,
                            C_id = 5
                        });
                });

            modelBuilder.Entity("StrucutredAPI1.Data.StudentCourse", b =>
                {
                    b.HasOne("StrucutredAPI1.Data.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("C_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrucutredAPI1.Data.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StrucutredAPI1.Data.Course", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("StrucutredAPI1.Data.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
